create table if not exists public.attendances (
  id bigint generated by default as identity primary key,
  employee_name text not null,
  work_date date not null,
  check_in time null,
  check_out time null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(employee_name, work_date)
);

alter table public.attendances enable row level security;

create policy "public read attendance" on public.attendances for select using (true);
create policy "public insert attendance" on public.attendances for insert with check (true);
create policy "public update attendance" on public.attendances for update using (true) with check (true);
