'use client';
import {useEffect,useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';

type Row={id?:number;work_date:string;check_in:string;check_out:string};
const names=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function minutes(i:string,o:string){if(!i||!o)return 0;const [ih,im]=i.split(':').map(Number),[oh,om]=o.split(':').map(Number);let a=ih*60+im,b=oh*60+om;if(b<=a)b+=1440;return b-a;}
export default function Page(){
 const [employee,setEmployee]=useState(''); const [start,setStart]=useState('2026-07-26'); const [end,setEnd]=useState('2026-08-25'); const [rows,setRows]=useState<Record<string,Row>>({}); const [status,setStatus]=useState('');
 const dates=useMemo(()=>{const out:Date[]=[];for(let d=new Date(start+'T00:00:00');d<=new Date(end+'T00:00:00');d.setDate(d.getDate()+1))out.push(new Date(d));return out},[start,end]);
 const total=dates.reduce((t,d)=>d.getDay()===5?t:t+minutes(rows[iso(d)]?.check_in||'',rows[iso(d)]?.check_out||''),0);
 async function load(){if(!employee)return;const {data,error}=await supabase.from('attendances').select('*').eq('employee_name',employee).gte('work_date',start).lte('work_date',end);if(error){setStatus(error.message);return}const map:Record<string,Row>={};(data||[]).forEach((r:any)=>map[r.work_date]={...r,check_in:r.check_in?.slice(0,5)||'',check_out:r.check_out?.slice(0,5)||''});setRows(map);setStatus('تم تحميل البيانات');}
 async function save(){if(!employee){setStatus('اكتب اسم الموظف أولًا');return}const payload=dates.filter(d=>d.getDay()!==5).map(d=>{const k=iso(d),r=rows[k]||{check_in:'',check_out:''};return {employee_name:employee,work_date:k,check_in:r.check_in||null,check_out:r.check_out||null}}).filter(r=>r.check_in||r.check_out);const {error}=await supabase.from('attendances').upsert(payload,{onConflict:'employee_name,work_date'});setStatus(error?error.message:'تم الحفظ في Supabase');}
 return <main><section className="card"><h1>نظام حساب دوام الموظفين</h1><div className="grid"><label>اسم الموظف<input value={employee} onChange={e=>setEmployee(e.target.value)}/></label><label>من<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>إلى<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><div className="actions"><button onClick={load}>تحميل</button><button onClick={save}>حفظ</button><span>{status}</span></div></section><section className="stats"><div>إجمالي الحضور<strong>{Math.floor(total/60)}س {total%60}د</strong></div><div>الساعات العشرية<strong>{(total/60).toFixed(4)}</strong></div><div>أيام العمل المكافئة<strong>{(total/480).toFixed(6)}</strong></div></section><section className="card tableWrap"><table><thead><tr><th>التاريخ</th><th>اليوم</th><th>الحضور</th><th>الانصراف</th><th>المدة</th><th>الأيام</th></tr></thead><tbody>{dates.map(d=>{const k=iso(d),fri=d.getDay()===5,r=rows[k]||{work_date:k,check_in:'',check_out:''},m=minutes(r.check_in,r.check_out);return <tr key={k} className={fri?'friday':''}><td>{k}</td><td>{names[d.getDay()]}</td>{fri?<td colSpan={4}>إجازة الجمعة</td>:<><td><input type="time" value={r.check_in} onChange={e=>setRows({...rows,[k]:{...r,check_in:e.target.value}})}/></td><td><input type="time" value={r.check_out} onChange={e=>setRows({...rows,[k]:{...r,check_out:e.target.value}})}/></td><td>{m?`${Math.floor(m/60)}س ${m%60}د`:'—'}</td><td>{m?(m/480).toFixed(6):'—'}</td></>}</tr>})}</tbody></table></section></main>
}