'use client';
import {useMemo,useState} from 'react';
import {supabase} from '@/lib/supabase';

type Row={id?:number;work_date:string;check_in:string;check_out:string};
const days=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
const shifts:any={morning:{label:'صباحي 06:00 → 14:00',start:'06:00',end:'14:00'},evening:{label:'مسائي 14:00 → 22:00',start:'14:00',end:'22:00'},flexible:{label:'مرن',start:'',end:''}};
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const toMin=(t:string)=>{if(!t)return 0;const[h,m]=t.split(':').map(Number);return h*60+m};
function worked(i:string,o:string){if(!i||!o)return 0;let a=toMin(i),b=toMin(o);if(b<=a)b+=1440;return b-a}
function analyze(r:Row,shift:string,lateGrace:number,earlyGrace:number){if(!r.check_in&&!r.check_out)return{status:'غياب',m:0,late:0,early:0};if(!r.check_in||!r.check_out)return{status:'معلق',m:0,late:0,early:0};const m=worked(r.check_in,r.check_out),s=shifts[shift];if(!s.start)return{status:'حضور',m,late:0,early:0};let ai=toMin(r.check_in),ao=toMin(r.check_out),si=toMin(s.start),so=toMin(s.end);if(so<=si)so+=1440;if(ao<=ai)ao+=1440;const rawLate=Math.max(0,ai-si),rawEarly=Math.max(0,so-ao);return{status:'حضور',m,late:rawLate>lateGrace?rawLate:0,early:rawEarly>earlyGrace?rawEarly:0}}
export default function Page(){
 const[employee,setEmployee]=useState('');const[start,setStart]=useState('2026-07-26');const[end,setEnd]=useState('2026-08-25');const[rows,setRows]=useState<Record<string,Row>>({});const[status,setStatus]=useState('');
 const[shift,setShift]=useState('morning');const[lateGrace,setLateGrace]=useState(15);const[earlyGrace,setEarlyGrace]=useState(5);
 const dates=useMemo(()=>{const out:Date[]=[];for(let d=new Date(start+'T00:00:00');d<=new Date(end+'T00:00:00');d.setDate(d.getDate()+1))out.push(new Date(d));return out},[start,end]);
 const summary=useMemo(()=>{let total=0,late=0,early=0,absent=0,pending=0;for(const d of dates){if(d.getDay()===5)continue;const a=analyze(rows[iso(d)]||{work_date:iso(d),check_in:'',check_out:''},shift,lateGrace,earlyGrace);total+=a.m;late+=a.late;early+=a.early;if(a.status==='غياب')absent++;if(a.status==='معلق')pending++;}return{total,late,early,absent,pending}},[dates,rows,shift,lateGrace,earlyGrace]);
 async function load(){if(!employee)return setStatus('اكتب اسم الموظف');const[{data:p},{data:a},{data:g}]=await Promise.all([supabase.from('employee_policies').select('*').eq('employee_name',employee).maybeSingle(),supabase.from('attendances').select('*').eq('employee_name',employee).gte('work_date',start).lte('work_date',end),supabase.from('app_settings').select('*').eq('id',1).maybeSingle()]);setLateGrace(g?.default_late_grace??15);setEarlyGrace(g?.default_early_grace??5);setShift(p?.shift_type||'morning');const map:Record<string,Row>={};(a||[]).forEach((r:any)=>map[r.work_date]={...r,check_in:r.check_in?.slice(0,5)||'',check_out:r.check_out?.slice(0,5)||''});setRows(map);setStatus('تم تحميل البيانات والإعدادات العامة');}
 async function save(){if(!employee)return setStatus('اكتب اسم الموظف');await supabase.from('app_settings').upsert({id:1,default_late_grace:lateGrace,default_early_grace:earlyGrace});await supabase.from('employee_policies').upsert({employee_name:employee,shift_type:shift},{onConflict:'employee_name'});const payload=dates.filter(d=>d.getDay()!==5).map(d=>{const k=iso(d),r=rows[k]||{check_in:'',check_out:''};return{employee_name:employee,work_date:k,check_in:r.check_in||null,check_out:r.check_out||null}}).filter(r=>r.check_in||r.check_out);if(payload.length)await supabase.from('attendances').upsert(payload,{onConflict:'employee_name,work_date'});setStatus('تم حفظ الدوام والإعدادات العامة');}
 return <main><section className="card"><h1>نظام حساب دوام الموظفين</h1><div className="grid"><label>اسم الموظف<input value={employee} onChange={e=>setEmployee(e.target.value)}/></label><label>الوردية<select value={shift} onChange={e=>setShift(e.target.value)}>{Object.entries(shifts).map(([k,v]:any)=><option key={k} value={k}>{v.label}</option>)}</select></label><label>سماح التأخير للجميع<input type="number" min="0" value={lateGrace} onChange={e=>setLateGrace(+e.target.value)}/></label><label>سماح الانصراف المبكر للجميع<input type="number" min="0" value={earlyGrace} onChange={e=>setEarlyGrace(+e.target.value)}/></label><label>من<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>إلى<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><div className="actions"><button onClick={load}>تحميل</button><button onClick={save}>حفظ</button><span>{status}</span></div></section><section className="stats"><div>إجمالي الحضور<strong>{Math.floor(summary.total/60)}س {summary.total%60}د</strong></div><div>أيام العمل<strong>{(summary.total/480).toFixed(6)}</strong></div><div>التأخير<strong>{summary.late} دقيقة</strong></div><div>الانصراف المبكر<strong>{summary.early} دقيقة</strong></div><div>الغياب<strong>{summary.absent}</strong></div><div>المعلق<strong>{summary.pending}</strong></div></section><section className="card tableWrap"><table><thead><tr><th>التاريخ</th><th>اليوم</th><th>الحضور</th><th>الانصراف</th><th>المدة</th><th>تأخير</th><th>مبكر</th><th>الحالة</th><th>الأيام</th></tr></thead><tbody>{dates.map(d=>{const k=iso(d),fri=d.getDay()===5,r=rows[k]||{work_date:k,check_in:'',check_out:''},a=analyze(r,shift,lateGrace,earlyGrace);return <tr key={k} className={fri?'friday':''}><td>{k}</td><td>{days[d.getDay()]}</td>{fri?<td colSpan={7}>إجازة الجمعة</td>:<><td><input type="time" value={r.check_in} onChange={e=>setRows({...rows,[k]:{...r,check_in:e.target.value}})}/></td><td><input type="time" value={r.check_out} onChange={e=>setRows({...rows,[k]:{...r,check_out:e.target.value}})}/></td><td>{a.m?`${Math.floor(a.m/60)}س ${a.m%60}د`:'—'}</td><td>{a.late||'—'}</td><td>{a.early||'—'}</td><td>{a.status}</td><td>{a.m?(a.m/480).toFixed(6):'—'}</td></>}</tr>})}</tbody></table></section></main>
}
