'use client';

import {useEffect,useMemo,useState} from 'react';
const AR=['الأحد','الاثنين','الثلاثاء','الأربعاء','الخميس','الجمعة','السبت'];
const pad=n=>String(n).padStart(2,'0');
const iso=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const fromISO=s=>{const[y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
const toMin=t=>{if(!t)return null;const[h,m]=t.split(':').map(Number);return h*60+m};
const uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;
function period(mode,month,cs,ce){if(mode==='custom')return{start:fromISO(cs),end:fromISO(ce)};const[y,m]=month.split('-').map(Number);return mode==='monthly'?{start:new Date(y,m-1,1),end:new Date(y,m,0)}:{start:new Date(y,m-2,26),end:new Date(y,m-1,25)}}
function worked(i,o){if(!i||!o)return 0;let a=toMin(i),b=toMin(o);if(b<=a)b+=1440;return b-a}
function scheduleFor(e,date){const first={start:e.shift1Start||'06:00',end:e.shift1End||'14:00',label:'الوردية 1'};if(e.shiftMode!=='dual')return first;const second={start:e.shift2Start||'14:00',end:e.shift2End||'22:00',label:'الوردية 2'};const anchor=fromISO(e.rotationStart||iso(new Date()));const d=fromISO(date);const week=Math.floor(Math.floor((d-anchor)/86400000)/7);return ((week%2)+2)%2===0?first:second}
function analyze(r,e,lateGrace,earlyGrace){if(r.friday)return{status:'جمعة',m:0,late:0,early:0,overtime:0,schedule:null};const s=scheduleFor(e,r.date);if(!r.checkIn&&!r.checkOut)return{status:'غياب',m:0,late:0,early:0,overtime:0,schedule:s};if(!r.checkIn||!r.checkOut)return{status:'معلق',m:0,late:0,early:0,overtime:0,schedule:s};const m=worked(r.checkIn,r.checkOut);let ai=toMin(r.checkIn),ao=toMin(r.checkOut),si=toMin(s.start),so=toMin(s.end);if(so<=si)so+=1440;if(ao<=ai)ao+=1440;const rl=Math.max(0,ai-si),re=Math.max(0,so-ao),overtime=Math.max(0,ao-so);return{status:'حضور',m,late:rl>lateGrace?rl:0,early:re>earlyGrace?re:0,overtime,schedule:s}}
function gen(start,end,old={}){const out=[];for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){const k=iso(d);out.push({date:k,day:AR[d.getDay()],friday:d.getDay()===5,checkIn:old[k]?.checkIn||'',checkOut:old[k]?.checkOut||''})}return out}
function sum(e,lg,eg){let total=0,late=0,early=0,overtime=0,absent=0,pending=0,fridays=0;for(const r of e?.rows||[]){const a=analyze(r,e,lg,eg);if(r.friday){fridays++;continue}total+=a.m;late+=a.late;early+=a.early;overtime+=a.overtime;if(a.status==='غياب')absent++;if(a.status==='معلق')pending++;}return{total,late,early,overtime,absent,pending,fridays,days:total/480}}
export default function Home(){
 const[employees,setEmployees]=useState([]),[activeId,setActiveId]=useState(''),[newName,setNewName]=useState('');const[lateGrace,setLateGrace]=useState(15),[earlyGrace,setEarlyGrace]=useState(5),[mode,setMode]=useState('cycle'),[month,setMonth]=useState('2026-08'),[cs,setCs]=useState('2026-07-26'),[ce,setCe]=useState('2026-08-25'),[loaded,setLoaded]=useState(false),[view,setView]=useState('employee');
 useEffect(()=>{try{const raw=localStorage.getItem('attendance-nextjs-standalone-v5');if(raw){const s=JSON.parse(raw);setEmployees(s.employees||[]);setActiveId(s.activeId||s.employees?.[0]?.id||'');setLateGrace(s.lateGrace??15);setEarlyGrace(s.earlyGrace??5);setMode(s.mode||'cycle');setMonth(s.month||'2026-08');setCs(s.cs||'2026-07-26');setCe(s.ce||'2026-08-25')}}finally{setLoaded(true)}},[]);useEffect(()=>{if(loaded)localStorage.setItem('attendance-nextjs-standalone-v5',JSON.stringify({employees,activeId,lateGrace,earlyGrace,mode,month,cs,ce}))},[loaded,employees,activeId,lateGrace,earlyGrace,mode,month,cs,ce]);
 const active=employees.find(e=>e.id===activeId)||employees[0]||null,p=useMemo(()=>period(mode,month,cs,ce),[mode,month,cs,ce]);const updateEmployee=(id,patch)=>setEmployees(x=>x.map(e=>e.id===id?{...e,...patch}:e));
 function add(){const name=newName.trim();if(!name)return;const id=uid();setEmployees(x=>[...x,{id,name,shiftMode:'single',shift1Start:'06:00',shift1End:'14:00',shift2Start:'14:00',shift2End:'22:00',rotationStart:'2026-07-26',rows:[]}]);setActiveId(id);setNewName('')}
 function buildAll(){setEmployees(x=>x.map(e=>{const old=Object.fromEntries((e.rows||[]).map(r=>[r.date,r]));return{...e,rows:gen(p.start,p.end,old)}}))}function updateRow(date,field,value){if(active)updateEmployee(active.id,{rows:active.rows.map(r=>r.date===date?{...r,[field]:value}:r)})}function fill(){if(!active)return;updateEmployee(active.id,{rows:active.rows.map(r=>{if(r.friday)return r;const s=scheduleFor(active,r.date);return{...r,checkIn:s.start,checkOut:s.end}})})}
 const summary=sum(active,Number(lateGrace)||0,Number(earlyGrace)||0),totals=employees.map(e=>({e,s:sum(e,Number(lateGrace)||0,Number(earlyGrace)||0)}));
 return <main><section className="hero no-print"><div><span className="eyebrow">Next.js Standalone</span><h1>حاسبة دوام الموظفين</h1><p>وردية واحدة أو ورديتان أسبوعيًا، مع احتساب الوقت الإضافي بعد نهاية الدوام.</p></div><div className="actions top-actions"><button onClick={()=>setView('employee')}>كشف الموظف</button><button onClick={()=>setView('summary')}>التقرير الإجمالي</button><button className="pdf" onClick={()=>window.print()}>تصدير / حفظ PDF</button></div></section>
 <section className="card no-print"><h2>الإعدادات العامة</h2><div className="grid"><label>سماح التأخير للجميع (دقيقة)<input type="number" min="0" value={lateGrace} onChange={e=>setLateGrace(e.target.value)}/></label><label>سماح الانصراف المبكر للجميع (دقيقة)<input type="number" min="0" value={earlyGrace} onChange={e=>setEarlyGrace(e.target.value)}/></label><label>إضافة موظف<div className="inline"><input value={newName} onChange={e=>setNewName(e.target.value)}/><button onClick={add}>إضافة</button></div></label><label>الفترة<select value={mode} onChange={e=>setMode(e.target.value)}><option value="monthly">شهر كامل</option><option value="cycle">26 → 25</option><option value="custom">مخصصة</option></select></label>{mode==='custom'?<><label>من<input type="date" value={cs} onChange={e=>setCs(e.target.value)}/></label><label>إلى<input type="date" value={ce} onChange={e=>setCe(e.target.value)}/></label></>:<label>الشهر<input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>}</div><div className="actions"><button onClick={buildAll}>إنشاء/تحديث الفترة للجميع</button></div><div className="employees-list">{employees.map(e=><button className={`employee-chip ${e.id===activeId?'selected':''}`} key={e.id} onClick={()=>{setActiveId(e.id);setView('employee')}}><span>{e.name}</span><small>{e.shiftMode==='dual'?'ورديتان أسبوعيًا':'وردية واحدة'}</small></button>)}</div></section>
 {view==='employee'&&active&&<><section className="card no-print"><h2>{active.name}</h2><div className="grid"><label>نظام الورديات<select value={active.shiftMode||'single'} onChange={e=>updateEmployee(active.id,{shiftMode:e.target.value})}><option value="single">وردية واحدة</option><option value="dual">ورديتان بالتناوب كل 7 أيام</option></select></label><label>بداية الوردية 1<input type="time" value={active.shift1Start||'06:00'} onChange={e=>updateEmployee(active.id,{shift1Start:e.target.value})}/></label><label>نهاية الوردية 1<input type="time" value={active.shift1End||'14:00'} onChange={e=>updateEmployee(active.id,{shift1End:e.target.value})}/></label>{active.shiftMode==='dual'&&<><label>بداية الوردية 2<input type="time" value={active.shift2Start||'14:00'} onChange={e=>updateEmployee(active.id,{shift2Start:e.target.value})}/></label><label>نهاية الوردية 2<input type="time" value={active.shift2End||'22:00'} onChange={e=>updateEmployee(active.id,{shift2End:e.target.value})}/></label><label>تاريخ بداية الدورة<input type="date" value={active.rotationStart||'2026-07-26'} onChange={e=>updateEmployee(active.id,{rotationStart:e.target.value})}/></label></>}</div><div className="actions"><button onClick={fill}>تعبئة أوقات الورديات تلقائيًا</button></div></section>
 <section className="stats policy-stats"><div><span>الحضور</span><strong>{Math.floor(summary.total/60)}س {summary.total%60}د</strong></div><div><span>أيام مكافئة</span><strong>{summary.days.toFixed(6)}</strong></div><div><span>الوقت الإضافي</span><strong>{Math.floor(summary.overtime/60)}س {summary.overtime%60}د</strong></div><div><span>التأخير</span><strong>{summary.late} د</strong></div><div><span>المبكر</span><strong>{summary.early} د</strong></div><div><span>الغياب</span><strong>{summary.absent}</strong></div><div><span>المعلق</span><strong>{summary.pending}</strong></div></section>
 <section className="card table-card"><table><thead><tr><th>التاريخ</th><th>اليوم</th><th>الوردية</th><th>الحضور</th><th>الانصراف</th><th>المدة</th><th>إضافي</th><th>التأخير</th><th>المبكر</th><th>الحالة</th></tr></thead><tbody>{(active.rows||[]).map(r=>{const a=analyze(r,active,Number(lateGrace)||0,Number(earlyGrace)||0);return <tr key={r.date} className={r.friday?'friday':''}><td>{r.date}</td><td>{r.day}</td>{r.friday?<td colSpan="8">إجازة الجمعة</td>:<><td>{a.schedule?.start} → {a.schedule?.end}</td><td><input type="time" value={r.checkIn} onChange={e=>updateRow(r.date,'checkIn',e.target.value)}/></td><td><input type="time" value={r.checkOut} onChange={e=>updateRow(r.date,'checkOut',e.target.value)}/></td><td>{a.m?`${Math.floor(a.m/60)}س ${a.m%60}د`:'—'}</td><td>{a.overtime?`${Math.floor(a.overtime/60)}س ${a.overtime%60}د`:'—'}</td><td>{a.late||'—'}</td><td>{a.early||'—'}</td><td>{a.status}</td></>}</tr>})}</tbody></table></section></>}
 {view==='summary'&&<section className="card table-card"><table><thead><tr><th>الموظف</th><th>النظام</th><th>الساعات</th><th>الأيام</th><th>الإضافي</th><th>التأخير</th><th>المبكر</th><th>غياب</th><th>معلق</th></tr></thead><tbody>{totals.map(({e,s})=><tr key={e.id}><td>{e.name}</td><td>{e.shiftMode==='dual'?'ورديتان أسبوعيًا':'وردية واحدة'}</td><td>{Math.floor(s.total/60)}س {s.total%60}د</td><td>{s.days.toFixed(6)}</td><td>{Math.floor(s.overtime/60)}س {s.overtime%60}د</td><td>{s.late}د</td><td>{s.early}د</td><td>{s.absent}</td><td>{s.pending}</td></tr>)}</tbody></table></section>}</main>
}
